name = "websitetacos"
compatibility_date = "2025-11-17"  # update to todayâ€™s date
# type field is not needed for static assets
# main field is not needed for static assets

[site]
bucket = "./tacostechnology"
entry-point = "."  # optional, tells Wrangler where to start
